#!/bin/bash
# Created by SharkPlush on GitHub
# https://github.com/SharkPlush
# Copyright 2025 SharkPlush
# Licensed under CC BY-NC 4.0 with attribution & change-indication requirements permanently waived by the author.
# No credit or change log required (appreciated though). Commercial use still forbidden.
# Full license: https://github.com/SharkPlush/Bash-AC-Power-Detection/blob/main/LICENSE
# Report any issues to https://github.com/SharkPlush/Bash-AC-Power-Detection/issues with logs.
set -euo pipefail
check_device () {
  if [[ "$(< /sys/class/dmi/id/chassis_type)" =~ ^(8|9|10|11|14|31|32)$ ]]; then
    echo "Detected a mobile device." 
    check_ac_status
    
  else
    echo "Device isn't a mobile device."
    example_executable # ADD WHATEVER YOU NEED TO RUN HERE
  fi
}
    
check_ac_status () { 
  if [[ "$(systemd-ac-power -v)" == "no" ]]; then
    echo "Device is unplugged waiting for AC power.."
    # RACE CONDITION HERE IF USER PLUGS IN AT THIS EXACT TIME (see issue 1 on GH)
    LPS="$(grep -m1 -oE "POWER_SUPPLY_ONLINE=[01]" <(udevadm monitor --subsystem-match=power_supply --property))"
    if [[ "$LPS" == "POWER_SUPPLY_ONLINE=1" ]]; then
      echo "Device is plugged in."
      example_executable # ADD WHATEVER YOU NEED TO RUN HERE
        
    elif [[ "$LPS" == "POWER_SUPPLY_ONLINE=0" ]]; then
      echo "A race condition happened exiting.."
      exit 1
    fi
  
  else
    echo "Device is plugged in." 
    example_executable # ADD WHATEVER YOU NEED TO RUN HERE
  fi
}
check_device
