#!/bin/bash
# Created by SharkPlush on GitHub
# https://github.com/SharkPlush
# Copyright 2025 SharkPlush
# Licensed under CC BY-NC 4.0 with attribution & change-indication requirements permanently waived by the author.
# No credit or change log required (appreciated though). Commercial use still forbidden.
# Full license: https://github.com/SharkPlush/Bash-AC-Power-Detection/blob/main/LICENSE
# Report any issues to https://github.com/SharkPlush/Bash-AC-Power-Detection/issues with logs.
set -euo pipefail
check_device () {
  if [[ $(< /sys/class/dmi/id/chassis_type) =~ ^(8|9|10|11|14|31|32)$ ]]; then
    echo "Detected a mobile device." 
    DD=$(upower -e | grep -E 'DisplayDevice')
    
    if [[ -z "$DD" ]]; then
      echo "Can't find the DisplayDevice path so AC status is undetermined, something might be wrong.."
      exit 1
  
    else
      check_ac_status
    fi
    
  else
    echo "Device isn't a mobile device."
    example_executable # ADD WHATEVER YOU NEED TO RUN HERE
  fi
}
    
check_ac_status () { 
  LPS=$(upower -i "$DD" | awk '/state:/ {print $2}')
  if [[ "$LPS" == "discharging" ]]; then
    echo "Device is unplugged waiting for AC power.."
    # RACE CONDITION HERE IF USER PLUGS IN AT THIS EXACT TIME (see issue 1 on GH)
    LPS=$(grep -m1 -oE "UINT32 [0-6]" <(busctl --system monitor --match "type='signal',sender='org.freedesktop.UPower',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='"$DD"',arg0='org.freedesktop.UPower.Device'"))
    if [[ "$LPS" =~ ^UINT32\ (1|5)$ ]]; then
      echo "Device is plugged in."
      example_executable # ADD WHATEVER YOU NEED TO RUN HERE
        
    elif [[ "$LPS" =~ ^UINT32\ (0|2)$ ]]; then
      echo "A race condition happened or couldn't determine the charging state exiting.."
      exit 1
    
    else
      echo "Unexpected battery state: $LPS report this to the GitHub page please! Exiting.."
      exit 1
    fi
      
  elif [[ "$LPS" =~ ^(charging|pending-charge)$ ]]; then
    echo "Device is plugged in."
    example_executable # ADD WHATEVER YOU NEED TO RUN HERE

  else
    echo "The AC state was unexpected, something might be wrong or your battery is missing" 
    exit 1
  fi
}
check_device
